### ISSUE TITLE
Two notes on two instruments occupying same space visually glitch

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#100]
**Describe the bug**
When rendering or playing a multi-instrument midi you can see the notes glitching inside each other if the two instruments are playing the same key at the same time, so the note occupies the same space. 

**To Reproduce**
1. Select a multi-insrument midi
2. Click on render or play
3. See the notes glitching

**Expected behavior**
Not this to happen

**Screenshots**
[
![sge](https://user-images.githubusercontent.com/55384029/78508774-b179dd00-7789-11ea-9173-01bbdfd0ddd9.png)
](url)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909 (OS Build 18363.720) 
 - Version 1.0.4

**Additional context**
The midi file: [RR_Project_M19_Mk_Va_Noctis.zip](https://github.com/LyricWulf/Embers/files/4434700/RR_Project_M19_Mk_Va_Noctis.zip)

**Comment by Naturalizze** [comment]
fixed in 1.0.5

**Comment by lyricwulf** [comment]
Fixed in [Embers 1.1.0](https://github.com/LyricWulf/Embers/releases/tag/1.1.0)
