### ISSUE TITLE
Rendering at non-standard aspect ratio does not fit render region to content

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#101]
**Describe the bug**
Rendering when display is not 16:9 requires user to manually crop empty space

**To Reproduce**
1. Resize the window to be some aspect ratio other than 16:9 
2. Render some midi file to video
3. The output video will be have black bars on the sides or top of the video, requiring the user to remove manually.

**Expected behavior**
Render output should be fit to content

**Screenshots**

![21:9](https://user-images.githubusercontent.com/9059018/78509005-f0dc0580-7758-11ea-8cfc-c2b9b6f46210.png)

![4:3](https://user-images.githubusercontent.com/9059018/78509161-1a496100-775a-11ea-89b7-f51445b35c90.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903 (OS Build 18362.719)
 - Version 1.0.4

**Additional Context:**
**Workaround:** Edit `GameUserSettings.ini` to have correct target resolution and render in windowed mode

**Comment by CowboyBepBop** [comment]
It's because it renders with the size of the window so if you change its ratio, the render ratio will also change

**Comment by lyricwulf** [comment]
Added in 2.1.1
