### ISSUE TITLE
Default Scroll Speed Option

### ISSUE THREAD

**Issue by samueldickenson** [LyricWulf/Embers#104]
When exporting video from Synthesia, I always have to open the MIDI in Synthesia first to adjust the scroll speed by the same amount each time to achieve the look I am after. Although it is a relatively quick manual task, it should be easily handled automatically by the software (if it already can be done in Synthesia, please notify me).

**Proposed solution:**
Include a menu item called "**Default Scroll Speed:**" (numerical value would likely be the best input). This would convert all incoming .mid files to the indicated scroll speed before playback/export.

**Comment by lyricwulf** [comment]
Included in 1.1! Thanks for the request! :D
