### ISSUE TITLE
Unable to render a midi on desktop

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#106]
**Describe the bug**
When rendering a midi placed on desktop, embers show the error "There was a problem initializing the output file. Try placing your MIDI in a different folder, avoiding any system or restricted folders".

**To Reproduce**
1. Set a midi wich is located on desktop
2. Click on render
3. The error message should  appears

**Expected behavior**
Embers should render the file correctly

**Screenshots**
[
![0](https://user-images.githubusercontent.com/55384029/78566208-2f3bf800-781f-11ea-93ef-819aff255820.png)
](url)

**Desktop (please complete the following information):**
 - OS: 10
 - Version 1.0.4

**Comment by Naturalizze** [comment]
try reinstalling the software and see if that helps

**Comment by CowboyBepBop** [comment]
Didn't do nothing
First uninstalled then re-installed

**Comment by Naturalizze** [comment]
note that in 1.0.5 this can happen some of the time, you click start over, then it works.

**Comment by lyricwulf** [comment]
Closing this as a stale support issue. If you need additional support, please submit a new issue.
