### ISSUE TITLE
discord link not working

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#107]
**Describe the bug**
When clicking on the "Get help on discord" button it shows an error

**To Reproduce**
1. Make Embers encounter an error so it display the "Get help on discord" button
2. Click on it
3. See the error pops up

**Expected behavior**
Embers shuld redirect to Embers discord

**Screenshots**
[
![7B323EA702E13BB0%21244850%3ACustomThumbnailSource%2CHighRes%2CDefault](https://user-images.githubusercontent.com/55384029/78566576-b5f0d500-781f-11ea-8c89-d4d51180b313.jpg)
](url)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home version 1909
 - Version 1.0.4

**Comment by Naturalizze** [comment]
fixed in 1.0.5

**Comment by lyricwulf** [comment]
Fixed in [Embers 1.1.0](https://github.com/LyricWulf/Embers/releases/tag/1.1.0)
