### ISSUE TITLE
Ember Flares adjustment settings

### ISSUE THREAD

**Issue by dafster** [LyricWulf/Embers#108]
**Is your feature request related to a problem? Please describe.**
Ember flares can sometimes make it difficult to see quick and intricate note patterns as they land on the notes, thereby making it potentially difficult for those following the tutorial.

**Describe the solution you'd like**
An option to either turn the opacity of the ember flares down, or another way to lower the intensity of them (eg: brightness)

**Describe alternatives you've considered**
Perhaps an option to place the ember flares behind the notes (though not sure if this would look good) or an option to turn of the flares completely.

**Additional context**

**Comment by lyricwulf** [comment]
There is an option to disable them, press Ctrl-E

:D
