### ISSUE TITLE
Main menu is just a black screen when pressing esc

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#109]
**Describe the bug**
Sometimes the main menu is just a black screen with the music on and you can't close Embers without killing it in the task manager

**To Reproduce**
1. Go in free play or render mode
2. Press the esc button
3. See the black screen

**Expected behavior**
Embers should go back to the main menu and behave properly

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise version 1909
 - Version 1.0.4

**Comment by CowboyBepBop** [comment]
Still present in version 1.2.0

**Comment by Naturalizze** [comment]
What are the specs of the PC that you're running this on. unable to reproduce.

**Comment by CowboyBepBop** [comment]
CPU: i7-8700k
GPU: RTX 2081ti 11Gb
RAM: 16Gb
Windows 10 Enterprise version 1909
