### ISSUE TITLE
Disabling embers in free play also disables notes

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#110]
**Describe the bug**
Disabling embers in free play also disables notes

**To Reproduce**
1. Begin free play
2. Disable embers (ctrl + E)
3. Begin playing
4. No notes are rendered

**Expected behavior**
Notes should be rendered regardless of embers

**Desktop (please complete the following information):**
 - Version 1.0.4

**Comment by lyricwulf** [comment]
Fixed in [Embers 1.1.0](https://github.com/LyricWulf/Embers/releases/tag/1.1.0)
