### ISSUE TITLE
Main menu background is just black

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#113]
**Describe the bug**
When launching Embers, instead of having the nice animation in the backgroud, it's just a black screen.

**To Reproduce**
1. Launch Embers
2. See the absence of background

**Expected behavior**
You should see the nice animation in the background.

**Screenshots**
[
![EmbersBug](https://user-images.githubusercontent.com/55384029/81127900-fdae6d80-8f3f-11ea-877d-24f1c13ff1aa.PNG)
](url)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise ver 1909
 - Embers version: 1.1.0

**Comment by Th3Gavst3r** [comment]
Same behavior here. 
Another observation: when loading into the menu, the screen appears solid white, then solid black, before settling on the correct background.
