### ISSUE TITLE
Improve note speed slider

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#122]
**Is your feature request related to a problem? Please describe.**
The slider for note speed changes size to fit its decimal precision, making selecting a specific speed very difficult.

**Describe the solution you'd like**
The note speed slider should stay a specific size, and have fewer significant digits for better readability

Additionally, note speed is not preserved between sessions. It would be nice to not have to change the value each time

**Comment by lyricwulf** [comment]
just a note that you can click the box to type in a number
