### ISSUE TITLE
Embers renders only one file

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#125]
**Describe the bug**
When rendering a midi, instead of outputing multiple files, it only outputs one avi file.

**To Reproduce**
1. Choose a midi
2. Render it with Embers
3. Go to the Embers Render folder
4. See that there is only one avi file and the script

**Expected behavior**
There should be multiple rendering files

**Screenshots**
![seg](https://user-images.githubusercontent.com/55384029/81228060-b088d500-8fed-11ea-9ad2-112ec3e39b26.PNG)

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10 Enterprise 1909
 - CPU: Intel i7-8700k
 - GPU: Nvidia RTX 2080ti 11gb
 - Embers Version: 1.1.0

**Comment by lyricwulf** [comment]
After some testing, this seems... ok for now. File segments were made to circumvent a fatal codec error but it seems to be fine for now. I'll be closely watching this to make sure this does not become an issue.

**Comment by CowboyBepBop** [comment]
Fixed in version 1.2.0
