### ISSUE TITLE
Resetting to default note colors causes fatal crash

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#128]
**Describe the bug**
Resetting to default note colors and then modifying the colors causes fatal crash when Patreon preview features are enabled.

**To Reproduce**
1. Authenticate as a Patreon supporter through Discord
2. In the play menu, click the "Return to default" button for note colors
3. Attempt to modify note colors
4. Crash to desktop

**Expected behavior**
No die

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903
 - CPU: Intel i7 6700k
 - GPU: Nvidia GeForce GTX 1070
 - Embers Version: 1.1.0

**Comment by CowboyBepBop** [comment]
Can reproduce.

**Desktop**
OS: Windows 10 Enterprise 2004
CPU:Intel i7-3632QM
GPU: Integrated intel graphism
Embers: Version 1.1.1

**Screenshot:**
![image](https://user-images.githubusercontent.com/55384029/81984197-bfe2d080-9634-11ea-9367-b9f501cba18c.png)

**Comment by Naturalizze** [comment]
issue still exists in 1.2
