### ISSUE TITLE
Changing perspective in 2D mode launches user into outer space

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#131]
**Describe the bug**
Changing perspective in 2D mode launches user into outer space

**To Reproduce**
1. Begin midi playback or free play
2. Enable 2D mode (`Ctrl` + `C`)
3. Change perspective (`Ctrl` + `-`)
4. Embers used seismic toss

**Expected behavior**
Launch aborted

**Screenshots**
[Example video](https://dl.dropboxusercontent.com/s/069hoow5e32to5g/important%20bug.mp4)

**Desktop (please complete the following information):**
 - Embers Version: 1.1.0

**Comment by lyricwulf** [comment]
This is a hilarious bug

**Comment by Naturalizze** [comment]
The alternate perspective has been removed from Embers.

**Comment by lyricwulf** [comment]
Closing as the secret perspective view is removed
