### ISSUE TITLE
128-key mode does not work in 2D mode

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#132]
**Describe the bug**
128-key mode does not work in 2D mode

**To Reproduce**
1. Enable 2D mode
4. Zoom out to 128-key view (mouse wheel)
5. Keyboard does not change size

**Expected behavior**
128-key mode should work in 2D mode

**Desktop (please complete the following information):**
 - Embers Version: 1.1.0

**Comment by CowboyBepBop** [comment]
Same bug when changing perspective
