### ISSUE TITLE
Mouse control does not work in 2D mode

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#133]
**Describe the bug**
Mouse control does not work in 2D mode

**To Reproduce**
1. Enable 2D mode
2. Click on piano keys
3. Nothing happens

**Expected behavior**
Mouse control should work in 2D mode

**Desktop (please complete the following information):**
 - Embers Version: 1.1.0

**Comment by Naturalizze** [comment]
still present in 1.2
