### ISSUE TITLE
Random ball mode

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#135]
**Describe the bug**
Using the keyboard, take control of ball-senpai and race your way to victory

**To Reproduce**
v1.0.4
1. Start free play
2. Hold the `E` key until the ball appears
3. Use `WASDQE` to control the ball's movement 

v1.1.1
1. Start free play
2. Hold `W` to move the ball out from under the piano's collision box
3. Hold the `E` key until the ball appears
4. Use `WASDQE` to control the ball's movement 

**Expected behavior**
Why is this even here

**Screenshots**
https://www.youtube.com/watch?v=MZyry9lpxHs

**Desktop (please complete the following information):**
 - Embers Version: 1.1.1

**Comment by CowboyBepBop** [comment]
Sadly fixed in version 1.2.0
