### ISSUE TITLE
Opening credits menu twice skyrockets memory usage and hangs Embers

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#137]
**Describe the bug**
Opening credits menu twice skyrockets memory usage and hangs Embers

**To Reproduce**
1. Open the credits menu
2. Leave the credits menu and navigate wherever you like, including free play
3. Open credits again
4. Embers rapidly maxes out system memory and becomes unresponsive

**Expected behavior**
None of that

**Screenshots**
Greedy greedy
![image](https://user-images.githubusercontent.com/9059018/82398952-0b74f000-9a22-11ea-99f2-739b42d46f3c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903
 - CPU: Intel i7 6700k
 - GPU: Nvidia GeForce GTX 1070
 - Embers Version: 1.2.0

**Comment by CowboyBepBop** [comment]
Verified and source of error identified.
Contact me on discord for more detailed information
