### ISSUE TITLE
Coolsoft VMS Failing to work with Embers Render

### ISSUE THREAD

**Issue by javaarchive** [LyricWulf/Embers#139]
**Describe the bug**
When rendering with Coolsoft VirtualMidi Synth

**To Reproduce**
Set Coolsoft VMS to the output device. You should see an error box at the top while rendering.
Image Missing due to the fact that I copied something else deleting the image from my clipboard and that I overwrote it.

**Expected behavior**
It should not get an error
**Screenshots**
 Trying to copy the image from discord once the slowmo ends. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903
 - CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
 - GPU: EVGA GTX 1080
 - Embers Version: 1.2.0.0

**Additional context**
Maybe just don't use the midi output for rendering at all.

**Comment by lyricwulf** [comment]
MIDI output is not used for rendering, that notice is related to midi input device and will not show up on the final render
