### ISSUE TITLE
Embers still sends midi data after closing a midi play

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#141]
**Describe the bug**
If you esc while Embers is still playing a midi, Embers sends the last midi instruction forever.
Easy to reproduce if you have loopmidi and any daw

**To Reproduce**
1. Select a midi file
2. Click on play
3. After letting Embers playing a bit press esc
4. See on the vst you're using that a midi instruction is still sent

**Expected behavior**
No midi instruction should be sent after closing a midi

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1909
 - CPU: Intel i7-8700k
 - GPU: Nvidia RTX 2080ti
 - Embers Version: 1.0.4/1.1.0/1.2.0/1.3.0.B

**Additional context**
Using Fruity Loops Studio and Serum vst

**Comment by lyricwulf** [comment]
When you say "sending a midi instruction" do you mean that the note is held?

**Comment by CowboyBepBop** [comment]
yes all the notes that were being pressed stay pressed
