### ISSUE TITLE
Exiting play modes while paused prevents transition to main menu

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#142]
**Describe the bug**
Exiting play modes while paused prevents transition to main menu

**To Reproduce**
1. Start any playback mode
2. Pause playback with `Tab` or `Enter`
3. Exit to main menu
4. Screen remains black indefinitely
5. Unpause with `Tab` or `Enter`
6. Transition completes

**Expected behavior**
Embers should return to main menu regardless of if playback is paused

**Desktop (please complete the following information):**
 - Embers Version: 1.2.0

**Comment by CowboyBepBop** [comment]
similar to #109

**Comment by Th3Gavst3r** [comment]
Probably worth noting that in this scenario you can quit the app using the `x` button or `Alt+F4` like normal, unlike #109 which requires a force quit
