### ISSUE TITLE
Dx11 Feature Level 10.0 is required to run the engine 

### ISSUE THREAD

**Issue by regohiro** [LyricWulf/Embers#149]
**Describe the bug**
Cannot open the app because of "dx11 Feature Level 10.0 is required to run the engine"

**To Reproduce**
Running Windows10 

**Expected behavior**
When trying to open the app

**Screenshots**
Error message: Dx11 Feature Level 10.0 is required to run the engine 

**Desktop (please complete the following information):**
 - OS: Windows 10 Education (Virtual Machine)
 - CPU: Core i5
 - GPU: --
 - Embers Version: 2.0

**Additional context**
I'm running Windows 10 in Virtual Machine on Macbook Pro

**Comment by regohiro** [comment]
P.S: I updated the drivers and Dx to the newest version but that did not solve the issue

**Comment by CowboyBepBop** [comment]
Duplicate of #92

**Comment by lyricwulf** [comment]
Closing as duplicate
