### ISSUE TITLE
Creator showcase doesn't redirect to videos

### ISSUE THREAD

**Issue by CowboyBepBop** [LyricWulf/Embers#151]
**Describe the bug**
When you click on a video in the creator showcase it doesn't open the video

**To Reproduce**
1. Click on the "Creator Showcase" button
2. Click on any video
3. Stay here without your video

**Expected behavior**
The video should pop up in your browser

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1909
 - CPU: Intel i7-8700k
 - GPU: Nvidia RTX 2080ti
 - Embers Version: 2.1.1

**Comment by lyricwulf** [comment]
Fixed in 2.1.2. Thank you!
