### ISSUE TITLE
Audio Will Not Play At All For MIDI and Live Play

### ISSUE THREAD

**Issue by EmbersFlying** [LyricWulf/Embers#155]
**Describe the bug**
After downloading Embers 2.2, The audio for any MIDI file or live play will not play at all. The music on the Main Menu still does. Never had this problem before the new update, please fix!

**Expected behavior**
Music would play normally.

**Desktop (please complete the following information):**
 - OS: Windows
 - CPU: Idk may update later
 - GPU: Idk may update later
 - Embers Version: 2.2

**Comment by Naturalizze** [comment]
this might be easier to discuss on Discord, in the #embers-support channel. 

https://embers.app/discord

**Comment by EmbersFlying** [comment]
> this might be easier to discuss on Discord, in the #embers-support channel.
> 
> https://embers.app/discord

I Do Not have discord, and I cannot get it for 2 months.

**Comment by Naturalizze** [comment]
go into settings and take a screenshot of that page and send it here.

**Comment by EmbersFlying** [comment]
> go into settings and take a screenshot of that page and send it here.

Which Page? Main Menu? MIDI Selection?

**Comment by Naturalizze** [comment]
Settings.

**Comment by EmbersFlying** [comment]
I found the problem! Apparently the update reset the settings for "output device". Thanks for helping!
