### ISSUE TITLE
Crashes when I try to load .mid file

### ISSUE THREAD

**Issue by Bobingstern** [LyricWulf/Embers#165]
**Describe the bug**
the app crashes whenever I try to load a .mid file or any file into it

**To Reproduce**
Click on play
Click on MIDI file
Load a file

**Expected behavior**
It should load the .mid file and run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU: Intel i7-10700F
 - GPU: Nvidia GeForce RTX 2060
 - Embers Version: 2.3

**Additional context**

**Comment by CowboyBepBop** [comment]
Can you please send the midi file?

**Comment by Bobingstern** [comment]
****

> Can you please send the midi file?
[Contra III The Alien Wars - Its Time for Revenge (1).zip](https://github.com/lyricwulf/Embers/files/7232009/Contra.III.The.Alien.Wars.-.Its.Time.for.Revenge.1.zip)

**Comment by Bobingstern** [comment]
It was just a bugged midi file. other files work fine for some reason

**Comment by CowboyBepBop** [comment]
[Contra III The Alien Wars - Its Time for Revenge.zip](https://github.com/lyricwulf/Embers/files/7232053/Contra.III.The.Alien.Wars.-.Its.Time.for.Revenge.zip)
The midi file had some bad data in it, here's the fixed version
