### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by asc11ts** [LyricWulf/Embers#170]
**Describe the bug**
No sound in whole Embers, volume on my Windows is 100%

**Expected behavior**
Just downloaded embers and no sound 💀👍

**Desktop**
 - OS: [Windows 11 Pro 23H2]
 - CPU: [Intel Core i5-12400F]
 - GPU: [Palit GeForce RTX 4060 Dual]
 - Embers Version: [2.3]

**Comment by CowboyBepBop** [comment]
Issue addressed in the Discord server.
