### ISSUE TITLE
BG cursor changes to window stretching arrow as opposed to staying a normal cursor

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#2]
![2020-03-25 19_39_44-Embers](https://user-images.githubusercontent.com/61640554/77598678-71387600-6ed0-11ea-834e-6b5fde313534.png)
![image](https://user-images.githubusercontent.com/61640554/77598661-667de100-6ed0-11ea-95c9-41197e221a97.png)

**Comment by lyricwulf** [comment]
Closing since sliders are changing in upcoming 1.3
