### ISSUE TITLE
Click and hold on file screen prevents you from going back

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#20]
**Describe the bug**
When on the file select screen, if you click and hold your curser on the back button and move it off, then your next click is to select a file, both the back button and the ESC key lose all functionality until you start playing a song, and it instantly closes the file select window upon doing this. 

https://i.gyazo.com/85c1cb03a1f5f09b795f863b3b2403b6.mp4

**To Reproduce**
1. Go to file select screen
2. Click and hold on Embers and then move your cursor off
3. Click to select a file

**Expected behavior**
Nothing to stop working and the closing animation for the file select window to function as intended

**Comment by LyricWulf** [comment]
fixed in 5.1
