### ISSUE TITLE
Audio glitches between version .4.0 and .4.1

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#23]
**Describe the bug**
clips and blips in the audio stream during playback, as well as visual lags which slow and speed up the tempo of the audio

**To Reproduce**
1. Listen to a midi in version .4.0 
2. listen to the same midi in version .4.1 

**Expected behavior**
The audio should be clear with no faults as well as the visuals.

**Screenshots**
.4.0: https://drive.google.com/open?id=1NFbPMLNwbqAy61LTPOei8WzvKfPre7t_ (there are a few glitches still here, but compare this to .4.1 and you'll see and hear the difference)
.4.1: https://drive.google.com/open?id=1v-w3DpQoHfGh9sk4JV4pq9eQha2mDmU5

**Additional context**
unsure exactly what's going on myself, but to the end user, the issue is with the audio, so that's how i'm reporting it

**Comment by LyricWulf** [comment]
fixed in 5.0
