### ISSUE TITLE
Midi file playback no longer has notes and audio is missing pedal sometimes

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#30]
**Describe the bug**
the notes that are to fall down for a midi file are no longer appearing. The audio for the midis is also not correct. it sounds as if the pedal works sometimes and not others. This wasn't an issue prior to this update. Even without any notes, the GPU utilization is now significantly higher.

**To Reproduce**
Play a midi file

**Screenshots**
https://drive.google.com/open?id=1hLTTh1HPPNbxk8diZDOsq_jDhciKdRAb

**Comment by LyricWulf** [comment]
oops.... fixed ahaha
