### ISSUE TITLE
trying to use the "return to default background button" after having selected a picture, gives a fatal error

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#31]
**Describe the bug**

**To Reproduce**
1. Go to file select screen
2. select a background 
3. click reset to default background

**Expected behavior**
It should switch to default background

**Screenshots**
![image](https://user-images.githubusercontent.com/61640554/77826918-8c79d000-70e0-11ea-997f-ce743f87a11e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LyricWulf** [comment]
fixed in 5.1
