### ISSUE TITLE
no text appears if image search returns nothing

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#33]
**Describe the bug**
no handler for no response from image categorization

**To Reproduce**
Not every image does this, but i have one that makes it do this. 
![1560 - Kirby And The Amazing Mirror (E)(Rising Sun)_01](https://user-images.githubusercontent.com/61640554/77827049-77ea0780-70e1-11ea-941f-63ef037a57af.png)

**Expected behavior**
something should appear here

**Screenshots**
![image](https://user-images.githubusercontent.com/61640554/77827011-42451e80-70e1-11ea-92d9-20bd191e8f23.png)

**Comment by LyricWulf** [comment]
Fixed. Now reads the file name instead of being blank
