### ISSUE TITLE
Cursor types a / after you type a : in the file select menu, anywhere in file path and won't allow you to backspace it

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#35]
**Describe the bug**
if you type a : in the file path, it will auto make a ``:/`` but then won't allow you to backspace it but highlighting both characters and backspacing works

**Expected behavior**
i was not expecting the :/ to appear. if it's intentional, that's fine, but it prevented me from  backspacing it. 

**Screenshots**
https://i.gyazo.com/417a8633480bc9b151af6eeaed360bf6.mp4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LyricWulf** [comment]
Fixed with other file picker bugs in 0.6.0
