### ISSUE TITLE
current controls no longer work

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#37]
**Describe the bug**
The controls listed on the file select screen haven't been updated to reflect the new "keybaord typing" layout, but the current controls no longer work (except ESC. that works). 

**Expected behavior**
The controls to be updated in the list, and functional

**Screenshots**
![image](https://user-images.githubusercontent.com/61640554/77827386-483bff00-70e3-11ea-800b-67ce320af058.png)

**Comment by LyricWulf** [comment]
Corrected in 5.1
