### ISSUE TITLE
Midi starts playing too early

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#38]
**Describe the bug**
Midi playback happens too early and occurs during the title sequence. 

(it also might start out of sync, but that could be the midi i chose in the video)

**Expected behavior**
There should be some delay after the title of the track

**Screenshots**
https://drive.google.com/open?id=1V0rDLVAAMc-RP0cQXOTUWJ0x4nS_pGTT

**Comment by LyricWulf** [comment]
Duplicate of #30
