### ISSUE TITLE
black keys have a 'shadow' of sorts in 3D mode

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#39]
**Describe the bug**
black keys have some weird shadow above them on the background in 3d mode

**Expected behavior**
this 'shadow' shouldn't be there

**Screenshots**
![image](https://user-images.githubusercontent.com/61640554/77827672-07dd8080-70e5-11ea-956a-82fdf02ef019.png)

**Comment by LyricWulf** [comment]
Fixed in 0.6.0
