### ISSUE TITLE
Background image search defaults to 'default' after you play a song with a background

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#40]
**Describe the bug**
after you select a background and go into midi playback/input mode, then exit and go back to the file select screen, your midi and background are still selected, however the background image categorization has returned to 'default' instead of either re-searching it or displaying the previous results

**To Reproduce**
1. play a song/midi input with a background
2. esc out of it
3. go to file select screen
4. See issue

**Expected behavior**
either re-searching it or displaying the previous results

**Screenshots**
https://i.gyazo.com/8789880386cad96f22498853555deb87.mp4

**Comment by LyricWulf** [comment]
Fixed in 5.1
