### ISSUE TITLE
Set file select to remember the previous location of midi/background on startup

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#41]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It would be cool if the software could save the previously selected folder i was in from the last time i started the program to something like a 'savegame' file. Down the line, with a creator version, this would probably be rather important.

**Comment by Naturalizze** [comment]
@LyricWulf in sure if the solution to this is the same as #68

**Comment by lyricwulf** [comment]
Added in 2.1.1
