### ISSUE TITLE
preview doesn't reflect the new style of key being pressed down

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#42]
**Describe the bug**
since the animated keys were introduced, the preview on the file select screen doesn't reflect the "key pressed down" state. Don't know if you want it to but it would properly reflect what it will look like in the playback. 

**Screenshots**
![image](https://user-images.githubusercontent.com/61640554/77828204-082b4b00-70e8-11ea-8992-9249c964b586.png)

**Comment by LyricWulf** [comment]
Fixed in 5.1
