### ISSUE TITLE
Font inconsistancies

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#44]
![image](https://user-images.githubusercontent.com/61640554/77828545-1da17480-70ea-11ea-9558-b5e85faa16d9.png)
![2020-03-28 11_47_27-Embers](https://user-images.githubusercontent.com/61640554/77828521-f9459800-70e9-11ea-8132-4f3db5600c0e.png)
![2020-03-28 11_39_51-Window](https://user-images.githubusercontent.com/61640554/77828522-f9459800-70e9-11ea-844c-d6de71e57d23.png)

I could be wrong but something here seems different than the rest, either font or theme wise

**Comment by LyricWulf** [comment]
Tidied up in 1.0.0 RC
