### ISSUE TITLE
File select screen 'close' is broken

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#50]
**Describe the bug**
After opening the file select screen, clicking outside of it no longer closes it as it did in previous versions. 

when you click ESC on the screen, the animation doesn't happen. 

after you hit ESC on the screen, ESC looses all functionality and you have to restart the game or play a midi/free play for it to work again

**Screenshots**
https://i.gyazo.com/024be281473bbb4cac1b4fa08903bbd9.mp4
https://i.gyazo.com/b266be04d8913945cf4e9330dabcbc0b.mp4

**Comment by LyricWulf** [comment]
Fixed in 0.6.0
