### ISSUE TITLE
watermark doesn't fade with midi title background

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#53]
**Expected behavior**
I expected it to fade.

**Screenshots**
![image](https://user-images.githubusercontent.com/61640554/77863923-8de3ef00-71eb-11ea-8e61-3cf99d92fb48.png)

this might be a bug, refactor, or intentional, i'm unsure

**Comment by LyricWulf** [comment]
Fixed in 0.6.0
