### ISSUE TITLE
button to deselect midi says "return to default" instead of "return to free play mode"

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#54]
**Expected behavior**
"Return to Free Play Mode"

**Screenshots**
![2020-03-29 18_30_25-Embers](https://user-images.githubusercontent.com/61640554/77863983-d00d3080-71eb-11ea-9a92-539ff1df4119.png)

**Comment by LyricWulf** [comment]
Fixed in 1.0.0 RC
