### ISSUE TITLE
EmbersBenchmark.txt is not being generated after a playthrough.

### ISSUE THREAD

**Issue by nkooman** [LyricWulf/Embers#55]
**Describe the bug**
`EmbersBenchmark.txt` is not being generated after a playthrough.

**To Reproduce**
1. Play a MIDI on default settings.
2. Allow the song to play all the through
3. Look for logfile at `C:\Program Files\Embers\Embers`

**Expected behavior**
EmbersBenchmark.txt to be generated at `C:\Program Files\Embers\Embers`.

**Environment**
 - OS: Windows 10

**Comment by LyricWulf** [comment]
At the moment the workaround is to run in admin mode. This is a Windows admin limitation when Embers is installed for all users.

**Comment by LyricWulf** [comment]
EmbersBenchmark.txt is no longer used
