### ISSUE TITLE
High GPU usage causes performance issues both inside and outside of the application.

### ISSUE THREAD

**Issue by nkooman** [LyricWulf/Embers#56]
**Describe the bug**
While the application is open, it uses a considerable amount of the GPU.
This also causing slowdowns and stutters during a playthrough.

**To Reproduce**
1. Open the application.
2. Check GPU usage.
3. Play a MIDI file.
4. Check GPU usage.

**Expected behavior**
Optimized performance that does not inhibit a playthrough or slow down a user's PC.

**Screenshots**
![image](https://user-images.githubusercontent.com/50636674/77867655-21c2b480-7206-11ea-97bc-35250da6c547.png)

**Environment**
 - OS: Windows 10
 - GPU: GTX 970
 - CPU: Intel 7700k

**Comment by Naturalizze** [comment]
@nkooman please check this on alpha version  1.0.2 and see if it's any better.

**Comment by nkooman** [comment]
@Naturalizze The problem still persists. I'll DM you the timestamp and MIDI I used.
![image](https://user-images.githubusercontent.com/50636674/78412506-99675980-75e1-11ea-94d4-7954f347e267.png)
