### ISSUE TITLE
File system navigation does not update address bar.

### ISSUE THREAD

**Issue by nkooman** [LyricWulf/Embers#57]
**Describe the bug**
When attempting to find a MIDI to by the file system navigator, clicking through folders does not update the address.

**To Reproduce**
1. Go to MIDI selection.
2. Navigate to `\Users` by clicking.
3. Navigate to `\{YourUserHere}` by clicking.
4. See that the address is not updated, nor can you use the back arrow to go back.

**Expected behavior**
Proper updates to the address bar when navigating.

**Screenshots**
Initial screen
![image](https://user-images.githubusercontent.com/50636674/77867891-28056080-7207-11ea-8b1d-a84b044ccde7.png)

After click on `Users`
![image](https://user-images.githubusercontent.com/50636674/77867945-61d66700-7207-11ea-8ef4-5fcd7b4cce0d.png)

After click on `Nick`
![image](https://user-images.githubusercontent.com/50636674/77867951-6a2ea200-7207-11ea-8082-5d729626ede5.png)

**Environment**
 - OS: Windows 10

**Comment by Naturalizze** [comment]
Noting that you can still type in navigation and it'll function, but you can't navigate by clicking. 

Also the user folder ends up being blank with nothing listed.

https://i.gyazo.com/e0da43fdd9bf7ed4ac09b0e1c4cf6830.mp4

**Comment by LyricWulf** [comment]
Fixed a lot of file select issues in 0.6.0
This should be fixed.
