### ISSUE TITLE
Cannot return to parent folder in MIDI select menu

### ISSUE THREAD

**Issue by Andrew123Shi** [LyricWulf/Embers#61]
**Describe the bug**
When selecting a MIDI in the file menu, if you access a file you can not return out of that file. In addition, the menu is permanently stuck on that file until the app is reopened.

**To Reproduce**
1. In the PLAY area, go to MIDI and click on File.
2. It should initially be in the Embers folder. Click on either Embers or Engine.
3. You are now stuck in that folder, back button does not work.

**Expected behavior**
Back button returns you to parent folder.

**Comment by LyricWulf** [comment]
Patched up in 0.6.0
