### ISSUE TITLE
Upper-right corner text is cut-off during play

### ISSUE THREAD

**Issue by Andrew123Shi** [LyricWulf/Embers#62]
**Describe the bug**
The upper right text of the UI is cut off while in play mode.

**To Reproduce**
1. Go to the PLAY page and press "PLAY"

**Expected behavior**
The text is fully there.

**Screenshots**
![cutoff](https://user-images.githubusercontent.com/49502693/77870774-2338b080-71f7-11ea-9d2b-11feebf8dd69.png)

**Comment by LyricWulf** [comment]
What is your screen aspect ratio? Is the window resized?

**Comment by Andrew123Shi** [comment]
> What is your screen aspect ratio? Is the window resized?

Screen aspect ratio is 16:10, 1920x1200.  I was playing in fullscreen mode.

**Comment by Naturalizze** [comment]
issue with aspect ratio might still be a thing but this text has been removed. leaving open for @LyricWulf 

we will need to test this before we can move forward.

**Comment by LyricWulf** [comment]
This issue is now out-of-date as the watermark design has changed
