### ISSUE TITLE
Fix the gaping space between A and Y in the PLAY header

### ISSUE THREAD

**Issue by Andrew123Shi** [LyricWulf/Embers#64]
**Describe the solution you'd like**
Adjust the kerning between the letters A and Y in PLAY in the header of the PLAY page. 

**Screenshot**
![play](https://user-images.githubusercontent.com/49502693/77871090-eb7e3880-71f7-11ea-8100-71570cf3f775.jpg)

**Comment by LyricWulf** [comment]
Thanks! Now appears as this in 1.0.0 RC

![image](https://user-images.githubusercontent.com/5668217/78059360-542bf900-734f-11ea-81be-078544cb536e.png)

**Comment by Andrew123Shi** [comment]
Beautiful
