### ISSUE TITLE
MIDI File Locked

### ISSUE THREAD

**Issue by AtlasWalker** [LyricWulf/Embers#65]
Upon selecting a MIDI File and playing it, Embers will keep playing it even when restarting the application or choosing a new MIDI File to play 

Steps to Reproduce the behavior:
1. Go to 'Select MIDI File'
2. Click on your MIDI
3. Play it
4. Exit using the escape key
5. Pick a New MIDI File 
6. Play It

The expected outcome will be that the first MIDI file you selected will be locked and will continue playing even when restarting the application.

 - OS: Windows 10 

Additional Context is that "Through The Fire and Flames" will kill your performance lol

**Comment by LyricWulf** [comment]
Can't reproduce. What do you mean by a MIDI file being locked?

**Comment by AtlasWalker** [comment]
Right now the problem seems to be solved with Embers 0.6.0

But for me, the first MIDI I played would be the only thing it would play
even if I restarted Embers or put in a new MIDI file.

**Comment by Naturalizze** [comment]
Was unable to replicate and doesn't appear to be an issue any longer.
