### ISSUE TITLE
Sixteenth notes/relatively short notes do not show up individually as short notes, but instead as one long note.

### ISSUE THREAD

**Issue by Andrew123Shi** [LyricWulf/Embers#66]
**Describe the bug**
Repeated 16th notes/short notes do not visually show up as individual notes in play mode, but combined into one long note. They still play as short notes though. 

**To Reproduce**
1. Play a MIDI with repeated 16th notes (in my case, Megalovania)

**Expected behavior**
Each individual note should be separated.

**Screenshots**
In Embers:
![temp](https://user-images.githubusercontent.com/49502693/78065689-7d955680-7348-11ea-8d80-4b58323c1851.png)
Actual music:
![temp 2](https://user-images.githubusercontent.com/49502693/78065700-81c17400-7348-11ea-8412-f10f32e30864.png)

Happens throughout the piece, not just at this one instance.

**Comment by Naturalizze** [comment]
Fixed in version 1.0.2
