### ISSUE TITLE
Application Crash in File Selector

### ISSUE THREAD

**Issue by andrewksmith12** [LyricWulf/Embers#67]
**Describe the bug**
File selector sometimes works fine, but sometimes entirely freezes the program, or crashes the program. 

**Desktop (please complete the following information):**
 - OS: Win10 1909 Fresh Install
 - Version 0.6.0

**Additional context**
I find that it doesn't crash as often if I click *wait 5 seconds* click while in file selector.

**Comment by Naturalizze** [comment]
fixed in alpha 1.0.2
