### ISSUE TITLE
File Selector for MIDI Starts in Application Folder

### ISSUE THREAD

**Issue by andrewksmith12** [LyricWulf/Embers#68]
**Is your feature request related to a problem? Please describe.**
File Selector for selecting a MIDI file always starts in application installation folder. This is not where most users will keep their data. 

**Describe the solution you'd like**
This should start in the User's root folder (%HOMEPATH%), in a folder created by embers within the user's home folder (I.e. %HOMEPATH%/Documents/Embers), or in the last folder accessed by the user (preserved between launches)

**Comment by Naturalizze** [comment]
unable to select file path due to potential platform information. For now, until new information is brought to us, this is unchangeable.

**Comment by LyricWulf** [comment]
%HOMEPATH% is not platform-agnostic

But I will see if could do something like this. Otherwise we will probably just save the last path.
