### ISSUE TITLE
Reboot during Installation

### ISSUE THREAD

**Issue by andrewksmith12** [LyricWulf/Embers#69]
**Describe the bug**
System Rebooted during installation of Embers 0.6.0 before the "Ask for reboot" stage of the installer. This is on a clean windows install. 

**Expected behavior**
Ask me to reboot, don't just do it :)

**Comment by Naturalizze** [comment]
Unable to verify this as every test we've run, asks to reboot but we've had a few people complain about this. Unable to accurately test, and installer issues are things relatively outside of our control *for now*.

**Comment by CowboyBepBop** [comment]
Fixed in version 1.2.0
