### ISSUE TITLE
Rendering Save Location

### ISSUE THREAD

**Issue by andrewksmith12** [LyricWulf/Embers#70]
**Describe the solution you'd like**
Save Renderings in a location within %USERPROFILE% or %HOMEPATH% instead of in AppData
OR 
Make that the default (Something in %HOMEPATH%) and let users select where they'd like outputs to be stored in settings (preserved between launches)

**Comment by Naturalizze** [comment]
Fixed in alpha 1.0; files now save in a generated folder called "embers render" in the same folder as your midi.
