### ISSUE TITLE
C:/ double discovery in file browser

### ISSUE THREAD

**Issue by Cupax3** [LyricWulf/Embers#72]
**Describe the bug**
C:/ appears two times when running file discovery

**To Reproduce**
1. Open file browser
2. Elevate to C:/
3. Enter C:/
4. Elevate again
5. Error

**Expected behavior**
Two C:/, identical in function, will be visible and selectable

**Screenshots**
![image](https://user-images.githubusercontent.com/5896309/78190108-a9f9c180-7473-11ea-93b1-fb81e02d9e45.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.0.0

**Additional context**
Not a priority

**Comment by Th3Gavst3r** [comment]
Behavior is duplicated across multiple drives:
![image](https://user-images.githubusercontent.com/9059018/78192970-540f2480-7447-11ea-9cbd-328674c4902f.png)

**Comment by Naturalizze** [comment]
This is a known issue with currently no known cause.

It also randomly happens with seemingly no specific way of triggering it directly.

**Comment by LyricWulf** [comment]
Fixed in [1.0.4](https://github.com/LyricWulf/Embers/releases/tag/1.0.4)
