### ISSUE TITLE
Embers freezes when user interaction on intro screen

### ISSUE THREAD

**Issue by Cupax3** [LyricWulf/Embers#73]
**Describe the bug**
Embers freezes on load if certain actions are performed on intro screen.

**To Reproduce**
1. Start embers
2. On logo, drag mouse around and click wildly
3. Error

**Expected behavior**
Complete application freeze, only taskmanager will help

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.0.0

**Additional context**
Quite cool

**Comment by Naturalizze** [comment]
Please update to version 1.0.2 and let us know what happens.

**Comment by Naturalizze** [comment]
@Cupax3 is there an update on this?

**Comment by Cupax3** [comment]
Seems fixed.
