### ISSUE TITLE
When program freezes it should close

### ISSUE THREAD

**Issue by IgorZev** [LyricWulf/Embers#80]
**Is your feature request related to a problem? Please describe.**
When some kind of crash happens the program freezes and you aren't able to do anything on your computer (it isn't always like that, which is interesting in its self). The only fix is to hard reset your computer.

**Describe the solution you'd like**
After a crash, the program should close automatically. Wich basically means there should be some kind of crash detection system

**Comment by Naturalizze** [comment]
This is related to an issue #82 and unsure how to resolve or modify. This is a hard crash and we're uncertain why or how to modify it.

**Comment by LyricWulf** [comment]
As of [1.0.4](https://github.com/LyricWulf/Embers/releases/tag/1.0.4) the freezing crashes are gone.
