### ISSUE TITLE
Crash in menu/after lyricwulf logo

### ISSUE THREAD

**Issue by MuskyS** [LyricWulf/Embers#82]
**Describe the bug**
Freezes in menu/after the lyricwulf logo and then eventually crashes.

**To Reproduce**
Startup the software

**Expected behavior**
For the software to not crash

Desktop:
 - OS: Windows 10
Gpu: 5.9 GB
Cpu: 2.30 GHz
Embers version 1.0.1

**Comment by Naturalizze** [comment]
Known issue; currently unknown what's causing it. it's seemingly random; possibly dependent on hardware spec

**Comment by LyricWulf** [comment]
Fixed in [1.0.4](https://github.com/LyricWulf/Embers/releases/tag/1.0.4)
