### ISSUE TITLE
the notes dont have sound

### ISSUE THREAD

**Issue by WalkerFox** [LyricWulf/Embers#83]
**Describe the bug**
when i press notes i dont hear any sound, i use the pc keyboard 

**To Reproduce**
1. Go to 'free play'
2. Click on 'any note'

**Expected behavior**
hear something

**Screenshots**
i guess dont heve any meaning

**Desktop (please complete the following information):**
 - OS: [win 10]

**Additional context**
when i try midi i dont hear the notes i press, but i hear the music

**Comment by Naturalizze** [comment]
Fixed in version 1.0.2
