### ISSUE TITLE
Midi Playback Sustains Indefinitely

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#85]
**Describe the bug**
Midi playback of multiple instruments causes instruments not on the first playback channel to sustain indefinitely

**To Reproduce**
1. Load a midi file with instruments on several channels
2. Play the file
3. The second instrument to play and all subsequent instruments not on the earliest playback channel will sustain forever

**Expected behavior**
Instruments should only sustain when they should

**Screenshots**
[Examle midi file](https://www.dropbox.com/s/uqzcs1bnbawz8zv/no%20sustain%20test%20FL.mid?dl=1)
[Example video](https://www.dropbox.com/s/ea7hcdwo6n738gg/Embers%20indefinite%20sustain%20example.mkv?dl=0)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903
 - Version 1.0.2

**Comment by LyricWulf** [comment]
Thank you! Fixed in [1.0.3](https://github.com/LyricWulf/Embers/releases/tag/1.0.3)
