### ISSUE TITLE
Playback hangs while moving or resizing window

### ISSUE THREAD

**Issue by 9hax** [lyricwulf/Embers#93]
**Describe the bug**
The whole program stops running while the titlebar is clicked or the window size is changed.

**To Reproduce**
1. Start Playback of a midi file in Embers
2. Change the Window Size or move the Window around on screen.

**Expected behavior**
The Playback should continue playing.

**Actual behaviour**
The Playback stops and resumes when the movement is over.

**Desktop (please complete the following information):**
 - OS: Windows 10 Insider Preview Build 2004/19592.1001
 - Version 1.0.4

**Comment by Naturalizze** [comment]
This is an issue that's present in other programs designed in this engine my AAA developers. Moving windows around when there's graphics involved is actually something very complicated for a computer to do, and is not something unreal seems to support.
