### ISSUE TITLE
background scales down on render

### ISSUE THREAD

**Issue by Naturalizze** [LyricWulf/Embers#96]
**Describe the bug**
at the start of a render on the file, the background scales down to fit the frame at the very beginning. 

**To Reproduce**
render a file
see the beginning

**Expected behavior**
this to not happen

**Desktop (please complete the following information):**
 - Version 1.0.4

**Additional context**
this bug is silly

**Comment by lyricwulf** [comment]
Fixed in [Embers 1.1.0](https://github.com/LyricWulf/Embers/releases/tag/1.1.0)
