### ISSUE TITLE
Silent failure when Midi input device cannot be enabled

### ISSUE THREAD

**Issue by Th3Gavst3r** [LyricWulf/Embers#98]
**Describe the bug**
When a midi device is locked by another application, Embers will appear to accept the device for input but will actually fail to enable it.

**To Reproduce**
1. Open any DAW and have it control your midi device
2. Open Embers' settings and select the same midi device for input
3. Begin free play
4. Notes played on the midi device will not be routed to Ember

**Expected behavior**
An error message should be shown when enabling a midi device fails.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903 (OS Build 18362.719)
 - Version 1.0.4

**Comment by Naturalizze** [comment]
bug confirmed @LyricWulf

**Comment by lyricwulf** [comment]
Fixed in 1.2 with a notice (which will be further refined in 1.3)
